export PATH=~/bin:$PATH
export PATH=~/bin/CustomScripts:$PATH
export PATH=~/bin/statusbar:$PATH
export PATH=~/bin/mystatus:$PATH
export PATH=$HOME/.config/npm-global:$PATH
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
#export VSCODE_PORTABLE= $XDG_CONFIG_HOME/vscode
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export XINITRC=$XDG_CONFIG_HOME/X11/xinitrc
